<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR9tRC9f\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR9tRC9f/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerR9tRC9f.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerR9tRC9f\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerR9tRC9f\App_KernelProdContainer([
    'container.build_hash' => 'R9tRC9f',
    'container.build_id' => '03c8d143',
    'container.build_time' => 1640279675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR9tRC9f');
