<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'workinprogress' => [[], ['_controller' => 'App\\Controller\\EventController::index'], [], [['text', '/marathon']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'success' => [[], ['_controller' => 'App\\Controller\\SuccessController::index'], [], [['text', '/success']], [], [], []],
];
