<?php

namespace ContainerH3n4aK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaolService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Maol' shared autowired service.
     *
     * @return \App\Controller\Maol
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\Maol'] = new \App\Controller\Maol();
    }
}
