<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQg67ROI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQg67ROI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQg67ROI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQg67ROI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQg67ROI\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qg67ROI',
    'container.build_id' => '28f85f7b',
    'container.build_time' => 1639232968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQg67ROI');
