<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWnud9bf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWnud9bf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWnud9bf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWnud9bf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWnud9bf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wnud9bf',
    'container.build_id' => 'bfc20a6a',
    'container.build_time' => 1640954694,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWnud9bf');
